version: '3'

services:
  mongodb:
    image: mongo:7.0.9
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

  auth-server:
    build: ./oauth/oauth
    ports:
      - "8082:8082"
    depends_on:
      - mongodb

  spring-boot-app:
    build: ./luiza-wishlist/luiza-wishlist
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - auth-server

volumes:
  mongodb_data:
