spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/wishlist-db
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-server:8082/.well-known/jwks.json
mongock:
  migration-scan-package: com.br.api.luizawishlist.wishlist
