spring:
  profiles:
    active: default
  data:
    mongodb:
      uri: mongodb://localhost:27017/wishlist-db
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8082/.well-known/jwks.json
mongock:
  migration-scan-package: com.br.api.luizawishlist.wishlist
